// A completed public sandbox run, observed through osmarmorales.io on 2026-09-10 UTC.
// Contains public outputs only. These are recorded observations, not live telemetry.
export const showcaseRun = {
  observed: '2026-09-10T02:28:25.725Z',
  durationMs: 20480,
  metrics: { agents: 3, tools: 4, sources: 3, briefs: 1, modelDecisions: 5 },
  sources: ['agent-factory', 'career', 'elygent'],
  members: [
    {
      id: 'researcher',
      name: 'Evidence researcher',
      role: 'Research',
      start: 0,
      end: 13139,
      calls: 2,
      color: '#418caf',
      task: 'Find the evidence behind the platform.',
      result:
        'Reviewed AI enablement platform adoption and Osmar’s platform ownership.',
    },
    {
      id: 'strategist',
      name: 'Platform strategist',
      role: 'Strategy',
      start: 0,
      end: 11404,
      calls: 2,
      color: '#7d86bd',
      task: 'Connect the work to leadership.',
      result: 'Examined governance, adoption, and the operating model.',
    },
    {
      id: 'editor',
      name: 'Executive editor',
      role: 'Synthesis',
      start: 13139,
      end: 20480,
      calls: 0,
      color: '#bb9966',
      task: 'Bring both perspectives together.',
      result: 'Delivered a concise executive brief with sources.',
    },
  ],
  events: [
    { type: 'agent_started', agent: 'researcher', ms: 0 },
    { type: 'agent_started', agent: 'strategist', ms: 0 },
    {
      type: 'tool_result',
      agent: 'strategist',
      tool: 'search_profile',
      ms: 5285,
    },
    {
      type: 'tool_result',
      agent: 'strategist',
      tool: 'inspect_project',
      ms: 5285,
    },
    {
      type: 'tool_result',
      agent: 'researcher',
      tool: 'search_profile',
      ms: 6673,
    },
    {
      type: 'tool_result',
      agent: 'researcher',
      tool: 'inspect_project',
      ms: 6674,
    },
    { type: 'agent_completed', agent: 'strategist', ms: 11404 },
    { type: 'agent_completed', agent: 'researcher', ms: 13139 },
    { type: 'handoff', agent: 'researcher', ms: 13139 },
    { type: 'handoff', agent: 'strategist', ms: 13139 },
    { type: 'agent_started', agent: 'editor', ms: 13139 },
    { type: 'agent_completed', agent: 'editor', ms: 20480 },
  ],
  answer:
    'Osmar demonstrates agent-platform leadership by architecting and operating Visa’s governed platform across tools, reusable skills, knowledge, model routing, human review, and multiple delivery modes, reaching 500+ total users through organic growth—evidence he can translate architecture into adoption. Next, assess broader leadership scope by probing governance tradeoffs, adoption mechanisms, operating ownership, and lessons from the independent Elygent pilot.',
};
